### ISSUE TITLE
Forking Your Web Page

### ISSUE THREAD

**Issue by syounkin** [kbroman/kbroman.github.io#3]
Hi Karl,

I am using your repository to learn how to make a nice web page.  I just wanted to let you know, in case it somehow disrupts your page.

If I create a web page from `syounkin/kbroman.github.io` will the link to [kbroman.org](http://kbroman.org/) be broken?  I wouldn't think so.  What happens?

Hope all is well.

Thanks.

Sam

**Comment by kbroman** [comment]
Hi, Sam,

I think you want to create syounkin/syounkin.github.io.
If you make syounkin/kbroman.github.io, it won't disrupt my own page, but it won't work for you, I don't think.

As I understand it, if you make a web page in the master branch of syounkin/syounkin.github.io, it'll show up at http://syounkin.github.io

For all other repositories, it'll look in the gh-pages branch, and if *you* have a repository named kbroman.github.io with the stuff in the gh-pages branch, it would show up at http://syounkin.github.io/kbroman.github.io

karl

**Comment by syounkin** [comment]
Thanks.  http://syounkin.github.io/kbroman.github.io now mirrors your page.

**Comment by kbroman** [comment]
It looks like there's a http/https issue. In the `_config.yml` file, I think you need to change instances of `http://` to `https://`.

**Comment by syounkin** [comment]
I'm having trouble getting the links to point to `syounkin.gtihub.io/kbroman.github.io` instead of just `syounkin.github.io`.  I presume it's in `_config.yml` file somewhere.  Any tips?

**Comment by kbroman** [comment]
In [line 19 of `_config.yml`](https://github.com/syounkin/syounkin.github.io/blob/kbroman/_config.yml#L19), I think you want:

    production_url : https://syounkin.github.io/kbroman.github.io

I think you can leave `BASE_PATH` (in [line 21](https://github.com/syounkin/syounkin.github.io/blob/kbroman/_config.yml#L21)) undefined (that is, comment that line out). It's needed only if it's different from `production_url`.

I don't *totally* understand this though, and I might be wrong.

**Comment by syounkin** [comment]
The issue persists.  The link for _About_ points to `https://syounkin.github.io/pages/about.html` instead of `https://syounkin.github.io/kbroman.github.io/pages/about.html`. (Or something like that.)

**Comment by kbroman** [comment]
I guess maybe try defining `BASE_PATH` to be the same as `production_url`.
